version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: dfindexer-redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: dfindexer-flaresolverr
    restart: unless-stopped
    network_mode: host
    environment:
      - LOG_LEVEL=info
      - TZ=America/Sao_Paulo

  indexer:
    image: ghcr.io/dflexy/dfindexer:latest
    container_name: dfindexer
    restart: unless-stopped
    network_mode: host
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - FLARESOLVERR_ADDRESS=http://localhost:8191
      - PORT=7006
      - LOG_LEVEL=1
      - LOG_FORMAT=console
      - TRACKER_SCRAPING_ENABLED=true
    depends_on:
      - redis
      - flaresolverr
